config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :admins

  root 'home#index'
  match '/products/:product_id' => 'home#show', via: :get

  match '/admins/products/:product_id/delete_image/:id' => 'admins/products#delete_image', via: :get

  resources :orders

  namespace :admins do
    namespace :products do
      post 'csv_upload'
    end
  end

  namespace :admins do
    resources :products
    resources :categories
    resources :orders
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :product_categories, dependent: :destroy
    has_many :products, through: :product_categories
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    enum status: [:draft, :published, :archived], _default: :draft

    has_many :product_categories, dependent: :destroy
    has_many :categories, through: :product_categories

    has_one_attached :primary_image
    has_many_attached :supporting_images

    validates :title, :description, :stock, presence: :true
    validates :stock, numericality: { greater_than_or_equal_to: 0 }
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/controllers/admins/categories_controller.rb
module Admins
  class CategoriesController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_category, only: %i[ show edit update destroy ]

    # GET /products or /products.json
    def index
      @categories = Category.all
    end

    # GET /products/1 or /products/1.json
    def show
    end

    # GET /products/new
    def new
      @category = Category.new
    end

    # GET /products/1/edit
    def edit
    end

    # POST /products or /products.json
    def create
      @category = Category.new(category_params)

      respond_to do |format|
        if @category.save
          format.html { redirect_to admins_category_path(@category), notice: "Category was successfully created." }
          format.json { render :show, status: :created, location: admins_category_path(@category) }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /products/1 or /products/1.json
    def update
      respond_to do |format|
        if @category.update(category_params)
          format.html { redirect_to admins_category_path(@category), notice: "Category was successfully updated." }
          format.json { render :show, status: :ok, location: admins_category_path(@category) }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /products/1 or /products/1.json
    def destroy
      @category.destroy
      respond_to do |format|
        format.html { redirect_to admins_categories_path, notice: "Category was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def category_params
        params.require(:category).permit(:name)
      end
  end
end

app/controllers/admins/orders_controller.rb
module Admins
    class OrdersController < ApplicationController
        before_action :authenticate_admin!

        def index
            @orders = Order.all
        end
    end
end

app/controllers/admins/products_controller.rb
module Admins
  class ProductsController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_product, only: %i[ show edit update destroy ]

    # GET /products or /products.json
    def index
      @products = Product.all

      respond_to do |format|
        format.html { }
        format.csv { send_data generate_csv(Product.all), file_name: 'products.csv' }
      end
    end

    # GET /products/1 or /products/1.json
    def show
    end

    # GET /products/new
    def new
      @product = Product.new
    end

    # GET /products/1/edit
    def edit
    end

    # POST /products or /products.json
    def create
      @product = Product.new(product_params)

      respond_to do |format|
        if @product.save
          format.html { redirect_to admins_product_path(@product), notice: "Product was successfully created." }
          format.json { render :show, status: :created, location: admins_product_path(@product) }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /products/1 or /products/1.json
    def update
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to admins_product_path(@product), notice: "Product was successfully updated." }
          format.json { render :show, status: :ok, location: admins_product_path(@product) }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /products/1 or /products/1.json
    def destroy
      @product.destroy
      respond_to do |format|
        format.html { redirect_to admins_products_path, notice: "Product was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    def csv_upload
      data = params[:csv_file].read.split("\n")
      data.each do |line| 
        col = line.split(",").map(&:strip)
        Product.create title: col[0], description: col[1], stock: col[2]
      end
      redirect_to action: :index
    end

    def delete_image
      image = ActiveStorage::Attachment.find(params[:id])
      image.purge
      redirect_to edit_admins_product_path(params[:product_id])
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_product
        @product = Product.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def product_params
        params.require(:product).permit(:title, :description, :stock, :status, :primary_image, supporting_images: [], category_ids: [])
      end

      def generate_csv(products)
        products.map { |p| [p.title, p.description, p.stock].join(',') }.join("\n")
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @products = Product.all
        render layout: "home"
    end

    def show
        @product = Product.find(params[:product_id])
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def new
        @order = Order.new
    end

    def create
        @order = Order.new(order_params)
  
        respond_to do |format|
          if @order.save
            format.html { redirect_to root_path, notice: "Order was successfully created." }
            format.json { render :show, status: :created, location: home_path }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @order.errors, status: :unprocessable_entity }
          end
        end
    end

    private

    def order_params
        params.require(:order).permit(:name, :product_name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/categories/_form.html.erb
<div class="my-5">
  <%= form_with(model: [:admins, category]) do |form| %>
    <% if category.errors.any? %>
      <div class="notification is-danger is-light" id="error_explanation">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
          <% category.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name, class: 'label' %>
      <div class="control">
        <%= form.text_field :name, class: 'input' %>
      </div>
    </div>

    <div class="action">
      <%= form.submit 'Submit', class: 'button is-primary is-outlined' %>
    </div>
  <% end %>
</div>

app/views/admins/categories/edit.html.erb
<h1 class="is-size-2 has-text-weight-bold mb-2">Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', admins_category_path(@category), class: 'button is-info is-outlined mr-3' %>
<%= link_to 'Back', admins_categories_path, class: 'button is-danger is-outlined' %>

app/views/admins/categories/index.html.erb
<div class="is-flex is-justify-content-space-between is-align-items-center">
  <h1 class="is-size-2 has-text-weight-bold mb-2">Categories</h1>
  <%= link_to '+ New Categories', new_admins_category_path, class: 'button is-link is-outlined' %>
</div>

<div class="table-container">
  <table class="table is-hoverable is-fullwidth">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td>
            <%= link_to admins_category_path(category), class: 'button is-small is-info is-outlined' do %>
              <i class="i fas fa-eye"></i>
            <% end %>
          </td>
          <td>
            <%= link_to edit_admins_category_path(category), class: 'button is-small is-success is-outlined' do %>
              <i class="i fas fa-pen"></i>
            <% end %>
          </td>
          <td>
            <%= link_to admins_category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-small is-danger is-outlined' do %>
              <i class="i fas fa-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admins/categories/new.html.erb
<h1 class="is-size-2 has-text-weight-bold mb-2">New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', admins_categories_path, class: 'button is-danger is-outlined' %>

app/views/admins/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<br>

<%= link_to 'Edit', edit_admins_category_path(@category), class: 'button is-success is-outlined mr-3' %>
<%= link_to 'Back', admins_categories_path, class: 'button is-danger is-outlined' %>

app/views/admins/orders/index.html.erb
<div class="is-flex is-justify-content-space-between is-align-items-center">
  <h1 class="is-size-2 has-text-weight-bold mb-2">Orders</h1>
</div>

<div class="table-container">
  <table class="table is-hoverable is-fullwidth">
    <thead>
      <tr>
        <th>Name</th>
        <th>Product Name</th>
        <th>Address</th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.name %></td>
          <td><%= order.product_name %></td>
          <td><%= order.address %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admins/products/_form.html.erb
<div class="my-5">
  <%= form_with(model: [:admins, product]) do |form| %>
    <% if product.errors.any? %>
      <div class="notification is-danger is-light" id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
        <ul>
          <% product.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :title, class: 'label' %>
      <div class="control">
        <%= form.text_field :title, class: 'input' %>
      </div>
    </div>

    <div class="field">
      <%= form.label :description, class: 'label' %>
      <div class="control">
        <%= form.text_area :description, class: 'textarea' %>
      </div>
    </div>

    <div class="field">
      <%= form.label :stock, class: 'label' %>
      <%= form.number_field :stock, class: 'input' %>
    </div>

    <div class="field">
      <%= form.label :categories, class: 'label' %>
      <div class="select is-multiple">
        <%= form.collection_select(:category_ids, Category.all, :id, :name, {}, {multiple: true}) %>
      </div>
    </div>

    <div class="field">
      <%= form.label :status, class: 'label' %>
      <div class="select">
        <%= form.select :status, Product.statuses.keys.map { |s| [s.humanize, s] } %>
      </div>
    </div>

    <div class="field mt-5">
      <% if product.primary_image.attached? %>
        <label class="label">Currently: <%= product.primary_image.filename %></label>
        <div class="is-inline-flex is-flex-direction-column is-align-items-center my-5">
          <%= image_tag product.primary_image, width: '150px', class: 'mb-3' %>
          <%= link_to 'X', '/admins/products/' + product.id.to_s + '/delete_image/' + product.primary_image.id.to_s, class: 'button is-danger is-outlined' %>
        </div>
      <% else %>
        <%= form.label :primary_image, class: 'label' %>
      <% end %>
      <div class="file has-name is-link">
        <label class="file-label">
          <%= form.file_field :primary_image, class: 'file-input' %>
          <span class="file-cta">
            <span class="file-icon">
              <i class="fas fa-upload"></i>
            </span>
            <span class="file-label">
              Choose a primary image
            </span>
          </span>
          <span class="file-name">
              No file uploaded
          </span>
        </label>
      </div>
    </div>

    <div class="field mt-5">
      <% if product.supporting_images.attached? %>
        <label class="label">Currently: 
          <%= product.supporting_images&.map(&:filename).join(', ') %>
        </label>
        <% product.supporting_images.each do |sp| %>
          <div class="is-inline-flex is-flex-direction-column is-align-items-center mr-2 my-5">
            <%= image_tag sp, width: '150px', class: 'mb-3' %>
            <%= link_to 'X', '/admins/products/' + product.id.to_s + '/delete_image/' + sp.id.to_s, class: 'button is-danger is-outlined' %>
          </div>
        <% end %>
      <% else %>
        <%= form.label :supporting_images, class: 'label' %>
      <% end %>
      <div class="file has-name is-info">
        <label class="file-label">
          <%= form.file_field :supporting_images, class: 'file-input', multiple: true %>
          <span class="file-cta">
            <span class="file-icon">
              <i class="fas fa-upload"></i>
            </span>
            <span class="file-label">
              Choose a supporting images
            </span>
          </span>
          <span class="file-name">
              No file uploaded
          </span>
        </label>
      </div>
    </div>

    <div class="action">
      <%= form.submit 'Submit', class: 'button is-primary is-outlined mt-3' %>
    </div>
  <% end %>
</div>

app/views/admins/products/edit.html.erb
<h1 class="is-size-2 has-text-weight-bold mb-2">Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', admins_product_path(@product), class: 'button is-info is-outlined mr-3' %>
<%= link_to 'Back', admins_products_path, class: 'button is-danger is-outlined' %>

app/views/admins/products/index.html.erb
<div class="is-flex is-justify-content-space-between is-align-items-center">
  <h1 class="is-size-2 has-text-weight-bold mb-2">Products</h1>
  <div>
    <%= link_to new_admins_product_path, class: 'button is-link is-outlined mr-1' do %>
      New Product<i class="fas fa-plus-circle ml-1"></i>
    <% end %>
    <%= link_to admins_products_path(format: :csv), class: 'button is-success is-outlined' do %>
      Download CSV<i class="fas fa-download ml-1"></i>
    <% end %>
  </div>
</div>

<div class="table-container">
  <table class="table is-hoverable is-fullwidth">
    <thead>
      <tr>
        <th>Primary Image</th>
        <th>Supporting Images</th>
        <th>Title</th>
        <th>Description</th>
        <th>Stock</th>
        <th>Category</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td>
            <% if product.primary_image.attached? %>
              <%= image_tag product.primary_image, width: '50px' %>
            <% end %>
          </td>
          <td>
            <% if product.supporting_images.attached? %>
              <% product.supporting_images.each do |i| %>
                <%= image_tag i, width: '50px' %>
              <% end %>
            <% end %>
          </td>
          <td><%= product.title %></td>
          <td><%= product.description %></td>
          <td><%= product.stock %></td>
          <td>
            <%= product.categories.empty? ? 'NA' : product.categories.map(&:name).join(', ') %>
          </td>
          <td><%= product.status.humanize %></td>
          <td>
            <%= link_to admins_product_path(product), class: 'button is-small is-info is-outlined' do %>
              <i class="i fas fa-eye"></i>
            <% end %>
          </td>
          <td>
            <%= link_to edit_admins_product_path(product), class: 'button is-small is-success is-outlined' do %>
              <i class="i fas fa-pen"></i>
            <% end %>
          </td>
          <td>
            <%= link_to admins_product_path(product), method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-small is-danger is-outlined' do %>
              <i class="i fas fa-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<h2 class="is-size-4 mb-2">Add new products from uploading CSV file.</h2>
<%= form_tag admins_products_csv_upload_path, multipart: true do %>
  <div class="file has-name is-link">
    <label class="file-label">
      <%= file_field_tag :csv_file, class: 'file-input' %>
      <span class="file-cta">
        <span class="file-icon">
          <i class="fas fa-upload"></i>
        </span>
        <span class="file-label">
          Choose a file…
        </span>
      </span>
      <span class="file-name">
        No file uploaded
      </span>
    </label>
  </div>
  
  <%= submit_tag :upload, class: 'button is-success mt-3' %>
<% end %>

app/views/admins/products/new.html.erb
<h1 class="is-size-2 has-text-weight-bold mb-2">New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', admins_products_path, class: 'button is-danger is-outlined' %>

app/views/admins/products/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.categories.empty? ? 'NA' : @product.categories&.map(&:name).join(', ') %>
</p>

<p>
  <strong>Status:</strong>
  <%= @product.status.humanize %>
</p>

<% if @product.primary_image.attached? %>
  <div class="my-3">
    <p><strong>Primary Image:</strong></p>
    <%= image_tag @product.primary_image, width: '250px', class: 'mb-2' %>
  </div>
<% end %>

<% if @product.supporting_images.attached? %>
  <div class="my-3">
    <p><strong>Supporting Images:</strong></p>
    <% @product.supporting_images.each do |image| %>
        <%= image_tag image, width: '250px', class: 'mb-2' %>
    <% end %>
  </div>
<% end %>

<br>

<%= link_to 'Edit', edit_admins_product_path(@product), class: 'button is-success is-outlined mr-3' %>
<%= link_to 'Back', admins_products_path, class: 'button is-danger is-outlined' %>

app/views/categories/_form.html.erb
<div class="my-5">
  <%= form_with(model: category) do |form| %>
    <% if category.errors.any? %>
      <div class="notification is-danger is-light" id="error_explanation">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
          <% category.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name, class: 'label' %>
      <div class="control">
        <%= form.text_field :name, class: 'input' %>
      </div>
    </div>

    <div class="action">
      <%= form.submit 'Submit', class: 'button is-primary is-outlined' %>
    </div>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="is-flex is-justify-content-space-between is-align-items-center">
  <h1 class="is-size-2 has-text-weight-bold mb-2">Categories</h1>
  <%= link_to '+ New Categories', new_category_path, class: 'button is-link is-outlined' %>
</div>

<div class="table-container">
  <table class="table is-hoverable">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td>
            <%= link_to category, class: 'button is-small is-info is-outlined' do %>
              <i class="i fas fa-eye"></i>
            <% end %>
          </td>
          <td>
            <%= link_to edit_category_path(category), class: 'button is-small is-success is-outlined' do %>
              <i class="i fas fa-pen"></i>
            <% end %>
          </td>
          <td>
            <%= link_to category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-small is-danger is-outlined' do %>
              <i class="i fas fa-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/new.html.erb
<h1 class="is-size-2 has-text-weight-bold mb-2">New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path, class: 'button is-danger is-outlined' %>

app/views/home/index.html.erb
<section class="hero is-medium is-dark">
    <div class="hero-body">
        <p class="title">
        Buy Best Products From All Of The World
        </p>
        <p class="subtitle mt-1">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod <br /> tempor incididunt ut labore et dolore magna.
        </p>
    </div>
</section>
<section class="section">
    <div class="container">
        <% if notice %>
            <div class="notification is-warning is-light"><%= notice %></div>
        <% end %>
        <% if alert %>
            <div class="notification is-danger is-light"><%= alert %></div>
        <% end %>
        <h2 class="is-size-3 mb-5">Our Products</h2>
        <div class="columns is-multiline">
            <% @products.each do |p| %>
                <div class="column is-3">
                    <%= link_to '/products/' + p.id.to_s do %>
                        <div class="card is-flex is-flex-direction-column" style="height: 100%;">
                            <div class="card-image">
                                <figure class="image is-4by3">
                                    <% if p.primary_image.attached? %>
                                        <%= image_tag p.primary_image %>
                                    <% end %>
                                </figure>
                            </div>
                            <div class="card-content is-flex-grow-1">
                                <div class="content" style="word-break: break-all">
                                    <h3 class="is-text-weight-bold is-size-5"><%= p.title %></h3>
                                    <p><%= p.description %></p>
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
            <% end %>
        </div>
    </div>
</section>

app/views/home/show.html.erb
<section class="section">
    <div class="container">
        <p>
        <strong>Title:</strong>
        <%= @product.title %>
        </p>

        <p>
        <strong>Description:</strong>
        <%= @product.description %>
        </p>

        <p>
        <strong>Stock:</strong>
        <%= @product.stock %>
        </p>

        <p>
        <strong>Category:</strong>
        <%= @product.categories.empty? ? 'NA' : @product.categories&.map(&:name).join(', ') %>
        </p>

        <% if @product.primary_image.attached? %>
        <div class="my-3">
            <p><strong>Primary Image:</strong></p>
            <%= image_tag @product.primary_image, width: '250px', class: 'mb-2' %>
        </div>
        <% end %>

        <% if @product.supporting_images.attached? %>
        <div class="my-3">
            <p><strong>Supporting Images:</strong></p>
            <% @product.supporting_images.each do |image| %>
                <%= image_tag image, width: '250px', class: 'mb-2' %>
            <% end %>
        </div>
        <% end %>

        <br>

        <%= link_to 'Buy Now', new_order_path, class: 'button is-primary is-outlined' %>

        <%= link_to 'Back', root_path, class: 'button is-danger is-outlined' %>
    </div>
</section>

app/views/layouts/partials/_nav.html.erb
<nav class="navbar is-white is-spaced has-shadow">
    <div class="navbar-brand">
        <%= link_to root_path, class: 'navbar-item has-text-weight-bold' do %>
            <i class="fas fa-dumpster mr-3"></i>MY-COMMERCE
        <% end %>
        <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
            <span></span>
            <span></span>
            <span></span>
        </a>
    </div>
    <div class="navbar-menu" id="navMenu">
        <div class="navbar-start">
            <% if admin_signed_in? %>
                <%= link_to admins_products_path, class: 'navbar-item' do %>
                    All Products<i class="fab fa-product-hunt ml-3"></i>
                <% end %>
                <%= link_to admins_categories_path, class: 'navbar-item' do %>
                    All Categories<i class="fas fa-beer ml-3"></i>
                <% end %>
                <%= link_to admins_orders_path, class: 'navbar-item' do %>
                    All Orders<i class="fas fa-sort ml-3"></i>
                <% end %>
            <% end %>
        </div>
        <div class="navbar-end">
            <% if admin_signed_in? %>
                <p class="navbar-item">Hi, <%= current_admin.email %></p>
                <%= link_to destroy_admin_session_path, method: :delete, class: 'navbar-item' do %>
                    Sign Out<i class="fas fa-sign-out-alt ml-3"></i>
                <% end %>
            <% else %>
                <%= link_to new_admin_session_path, class: 'navbar-item' do %>
                    Login<i class="fas fa-sign-in-alt ml-3"></i>
                <% end %>
                <%= link_to new_admin_registration_path, class: 'navbar-item' do %>
                    Sign Up<i class="fas fa-user-plus ml-3"></i>
                <% end %>
            <% end %>
        </div>
    </div>
</nav>

app/views/orders/new.html.erb
<h1 class="is-size-2 has-text-weight-bold mb-2">New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', root_path, class: 'button is-danger is-outlined' %>

app/views/products/index.html.erb
<div class="is-flex is-justify-content-space-between is-align-items-center">
  <h1 class="is-size-2 has-text-weight-bold mb-2">Products</h1>
  <div>
    <%= link_to new_product_path, class: 'button is-link is-outlined mr-1' do %>
      New Product<i class="fas fa-plus-circle ml-1"></i>
    <% end %>
    <%= link_to products_path(format: :csv), class: 'button is-success is-outlined' do %>
      Download CSV<i class="fas fa-download ml-1"></i>
    <% end %>
  </div>
</div>

<div class="table-container">
  <table class="table is-hoverable">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Stock</th>
        <th>Category</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.title %></td>
          <td><%= product.description %></td>
          <td><%= product.stock %></td>
          <td>
            <%= product.categories.empty? ? 'NA' : product.categories.map(&:name).join(', ') %>
          </td>
          <td><%= product.status.humanize %></td>
          <td>
            <%= link_to product, class: 'button is-small is-info is-outlined' do %>
              <i class="i fas fa-eye"></i>
            <% end %>
          </td>
          <td>
            <%= link_to edit_product_path(product), class: 'button is-small is-success is-outlined' do %>
              <i class="i fas fa-pen"></i>
            <% end %>
          </td>
          <td>
            <%= link_to product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-small is-danger is-outlined' do %>
              <i class="i fas fa-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= form_tag products_csv_upload_path, multipart: true do %>
  <div id="file-js-example" class="file has-name is-link">
    <label class="file-label">
      <%= file_field_tag :csv_file, class: 'file-input' %>
      <span class="file-cta">
        <span class="file-icon">
          <i class="fas fa-upload"></i>
        </span>
        <span class="file-label">
          Choose a file…
        </span>
      </span>
      <span class="file-name">
        No file uploaded
      </span>
    </label>
  </div>
  <%= submit_tag :upload, class: 'button is-success mt-3' %>
<% end %>

app/views/products/new.html.erb
<h1 class="is-size-2 has-text-weight-bold mb-2">New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path, class: 'button is-danger is-outlined' %>

app/views/products/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.categories.empty? ? 'NA' : @product.categories.map(&:name).join(', ') %>
</p>

<p>
  <strong>Status:</strong>
  <%= @product.status.humanize %>
</p>

<br>

<%= link_to 'Edit', edit_product_path(@product), class: 'button is-success is-outlined mr-3' %>
<%= link_to 'Back', products_path, class: 'button is-danger is-outlined' %>